= Cargo

Cargo is Rust’s build system and package manager footnote:[Cargo is to Rust what https://maven.apache.org/[Maven] is to Java].

Cargo is included with the standard Rust distribution.

* Create a project

[source, cmd]
----
cargo new hello_cargo
----

This will create the binary (application) `hello_cargo` package in the `hello_cargo` directory.

----
.
├── .git <1>
├── .gitignore <1>
├── Cargo.toml <2>
└── src
    └── main.rs
----
<1> A Git repository is initialized
<2> Why use https://toml.io/en/[TOML]?

====
[source, toml]
.`Cargo.toml`
----
[package]
name = "hello_cargo" <1>
version = "0.1.0" <2>
edition = "2021" <3>

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] <4>
----
<1> Program name
<2> Program version
<3> Rust edition
<4> Dependencies
====

* Build project

[source, cmd]
----
cargo build
----

The binary executable `hello_cargo` is placed in the `target/debug` directory because the default build is a debug build.

* Run

[source, cmd]
----
./target/debug/hello_cargo
----

We can also use the following command:

[source, cmd]
----
cargo run <1>
----
<1> The `run` command automatically rebuilds the project if needed

If you just want to check that your project compiles properly, you can use the following command:

[source, cmd]
----
cargo check
----

* Release

[source, cmd]
----
cargo build --release
----

The *optimized* binary is placed in the `target/release` directory.

== Dependency management

When we include an external dependency, Cargo fetches the latest compatible versions of all the crates that dependency needs from the registry footnote:[The default registry is https://crates.io[Crates.io]. This is where people in the Rust ecosystem post their open source Rust projects for others to use.]. +

A new file named `Cargo.lock` footnote:[This is the equivalent of https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json[`package-lock.json`] for npm] is created at the top level with the exact versions of the dependencies computed in the previous step.

When you build your project in the future, Cargo will see that the `Cargo.lock` file exists and will use the versions specified there rather than doing all the work of figuring out versions again. +
If you want Cargo to ignore that file and compute the versions again, use the `cargo update` command.

After downloading the crates, Rust compiles them and then compiles the project with the dependencies available.

* Documentation

If you have dependencies, the following command will build documentation provided by all your dependencies locally footnote:[In the `target/doc` directory] and open it in your browser:

[source, cmd]
----
cargo doc --open
----